# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go
sudo: false

go:
  - 1.11.x
  - 1.12.5

git:
  depth: 1

env:
  global:
    - CC_TEST_REPORTER_ID="93e68dc1e77ab000681ed8f82cba217fbc9d7ac18fd3c4b81ecc889076da2dcf"

before_install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - export GO111MODULE=off
  - dep ensure
  - golangci-lint run

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - CGO_ENABLED=0
  - go test -v -race ./... -coverprofile=c.out -covermode=atomic

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT